#!/usr/bin/perl

##
## Copyright 2008 Adriana Lukas & Alec Muffett
##
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License. You
## may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
## implied. See the License for the specific language governing
## permissions and limitations under the License.
##

# performs a sweep of perl scripts given as arguments, looking for
# undefined function calls

@input = <>;

foreach $line (@input) {
    $line =~ s!#.*!!o;
    $calls{$1}++ while ($line =~ s!\&(\w+)!!go);
}

foreach $func (sort keys %calls) {
    print "$func";
    print " undefined" unless (grep(/sub\s+$func/, @input));
    print "\n";
}

